/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import entidade.EAgendaAtendimento;
import entidade.EFilaPaciente;
import entidade.EMedico;
import entidade.EPaciente;
import entidade.EProntuario;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Vector;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Roberval
 */
public class AgendaAtendimento extends javax.swing.JInternalFrame {

    JDesktopPane principal;
    java.sql.Date dataconsulta;
    EPaciente paciente;
    EMedico medico;
    PacienteCadastro cadastroPaciente;

    public AgendaAtendimento() {
        initComponents();
    }

    public AgendaAtendimento(JDesktopPane instancia) {
        this();
        principal = instancia;

    }

    public Date getDataconsulta() {
        return dataconsulta;
    }

    public void setDataconsulta(Date dataconsulta) {
        this.dataconsulta = dataconsulta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldMedico = new javax.swing.JTextField();
        jTextFieldPaciente = new javax.swing.JTextField();
        jLabelDataAgendamento = new javax.swing.JLabel();
        jFormattedTextFieldDataAgendamento = new javax.swing.JFormattedTextField();
        jLabelEspecialidade = new javax.swing.JLabel();
        jTextFieldEspecialidade = new javax.swing.JTextField();
        jLabelAgenda = new javax.swing.JLabel();
        jButtonFechar = new javax.swing.JButton();
        jButtonIncluir = new javax.swing.JButton();
        jButtonPesquisaMedico = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonPesquisaPaciente = new javax.swing.JButton();
        jButtonPesquisaAgenda = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableResultadoPesquisa = new javax.swing.JTable();

        setTitle("Agendamento de consulta");

        jLabelDataAgendamento.setText("Data/Hora Agendamento");

        try {
            jFormattedTextFieldDataAgendamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####, ##:##hrs")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelEspecialidade.setText("Especialidade");

        jLabelAgenda.setText("Agenda de Atendimentos");

        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jButtonIncluir.setText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        jButtonPesquisaMedico.setText("Pesquisa Médico");
        jButtonPesquisaMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaMedicoActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");

        jButtonPesquisaPaciente.setText("Pesquisa Paciente");
        jButtonPesquisaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaPacienteActionPerformed(evt);
            }
        });

        jButtonPesquisaAgenda.setText("Pesquisa Agenda");

        jTableResultadoPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableResultadoPesquisa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPaciente)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelDataAgendamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(147, 147, 147))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonPesquisaPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(148, 148, 148))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jFormattedTextFieldDataAgendamento)
                                        .addGap(131, 131, 131)))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelEspecialidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(203, 203, 203))
                                    .addComponent(jTextFieldMedico)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonPesquisaMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(156, 156, 156))
                                    .addComponent(jTextFieldEspecialidade)))
                            .addComponent(jScrollPane2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonPesquisaAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabelAgenda)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPesquisaPaciente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDataAgendamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldDataAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPesquisaMedico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelEspecialidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(jLabelAgenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPesquisaAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButtonFechar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisaMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaMedicoActionPerformed


    }//GEN-LAST:event_jButtonPesquisaMedicoActionPerformed

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed

        try {

//            paciente = PesquisaPaciente.busca();
            EAgendaAtendimento agenda = new EAgendaAtendimento();
            agenda.setPaciente(paciente);

            agenda.getMedico().setNome(jTextFieldMedico.getText());
            agenda.getMedico().setEspecialidade(jTextFieldEspecialidade.getText());
            agenda.getPaciente().setNome(jTextFieldPaciente.getText());
            agenda.setDataHoraAgendamento(jFormattedTextFieldDataAgendamento.getText());

            new negocio.NAgendaAtendimento().salvar(agenda);

//            LISTA OS DADOS NA GRID
            Vector<String> grid = new Vector<String>();
            grid.add("Paciente");
            grid.add("Médico");
            grid.add("Especialidade");
            grid.add("Data/Hora");

            List<EAgendaAtendimento> retorno = new negocio.NAgendaAtendimento().listar(agenda);

            Vector detalhe = new Vector();

            for (EAgendaAtendimento item : retorno) {
                Vector<Object> linha = new Vector<>();
                linha.add(item.getPaciente().getNome());
                linha.add(item.getMedico().getNome());
                linha.add(item.getMedico().getEspecialidade());
                linha.add(item.getDataHoraAgendamento());
                detalhe.add(linha);
            }

            jTableResultadoPesquisa.setModel(new DefaultTableModel(detalhe, grid));

            jTextFieldMedico.setText("");
            jTextFieldPaciente.setText("");
            jFormattedTextFieldDataAgendamento.setText("");
            jTextFieldEspecialidade.setText("");

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(principal, erro.getMessage());
        }


    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonPesquisaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaPacienteActionPerformed

        try {
            
            PesquisaPaciente pesquisa = new PesquisaPaciente(this.principal);
            principal.add(pesquisa);
            pesquisa.setVisible(true);
            
            

//            PacienteCadastro cadastroPaciente = new PacienteCadastro(this, this.principal);
//            principal.add(cadastroPaciente);
//            cadastroPaciente.setVisible(true);
//            this.setVisible(false);
//            this.dispose();

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(principal, erro.getMessage());
        }


    }//GEN-LAST:event_jButtonPesquisaPacienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonPesquisaAgenda;
    private javax.swing.JButton jButtonPesquisaMedico;
    private javax.swing.JButton jButtonPesquisaPaciente;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataAgendamento;
    private javax.swing.JLabel jLabelAgenda;
    private javax.swing.JLabel jLabelDataAgendamento;
    private javax.swing.JLabel jLabelEspecialidade;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableResultadoPesquisa;
    private javax.swing.JTextField jTextFieldEspecialidade;
    private javax.swing.JTextField jTextFieldMedico;
    private javax.swing.JTextField jTextFieldPaciente;
    // End of variables declaration//GEN-END:variables
}
