/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import entidade.EAgendaAtendimento;
import entidade.EFilaPaciente;
import entidade.EPaciente;
import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JDesktopPane;
import javax.swing.JTextField;
import sun.java2d.pipe.SpanShapeRenderer;

/**
 *
 * @author Roberval
 */
public class PacienteCadastro extends javax.swing.JInternalFrame {

    JDesktopPane principal;
    AgendaAtendimento agenda;

    /**
     * Creates new form PacienteCadastro
     */
    public PacienteCadastro() {
        initComponents();
        jTextFieldNome.setEnabled(false);
        jTextFieldId.setEnabled(false);
        jTextFieldMae.setEnabled(false);
        jTextFieldPai.setEnabled(false);
        jTextFieldSexo.setEnabled(false);
        jTextFieldEndereco.setEnabled(false);
        jFormattedTextFieldCpf.setEnabled(false);
        jFormattedTextFieldDataNascimento.setEnabled(false);
        jFormattedTextFieldRg.setEnabled(false);
        jFormattedTextFieldTelefone.setEnabled(false);

    }

    public PacienteCadastro(AgendaAtendimento agenda, JDesktopPane instancia) {
        this();
        this.principal = instancia;
        this.agenda = agenda;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelInscricao = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelSexo = new javax.swing.JLabel();
        jTextFieldSexo = new javax.swing.JTextField();
        jLabelDataNascimento = new javax.swing.JLabel();
        jLabelCpf = new javax.swing.JLabel();
        jLabelRg = new javax.swing.JLabel();
        jLabelMae = new javax.swing.JLabel();
        jLabelPai = new javax.swing.JLabel();
        jLabelEndereco = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldMae = new javax.swing.JTextField();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        jTextFieldEndereco = new javax.swing.JTextField();
        jTextFieldPai = new javax.swing.JTextField();
        jButtonAgendarAtendimento = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jFormattedTextFieldDataNascimento = new javax.swing.JFormattedTextField();
        jFormattedTextFieldRg = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCpf = new javax.swing.JFormattedTextField();
        jButtonLimpar = new javax.swing.JButton();
        jComboBoxPesquisar = new javax.swing.JComboBox();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setTitle("Cadastro de pacientes");

        jLabel6.setFont(new java.awt.Font("Rod", 0, 18)); // NOI18N
        jLabel6.setText("CM");

        jLabel1.setFont(new java.awt.Font("Rod", 0, 14)); // NOI18N
        jLabel1.setText("Dados básicos");

        jLabelInscricao.setText("Inscriçao");

        jTextFieldId.setEditable(false);

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jLabelNome.setText("Paciente");

        jLabelSexo.setText("Sexo");

        jLabelDataNascimento.setText("Data de Nascimento");

        jLabelCpf.setText("CPF");

        jLabelRg.setText("RG");

        jLabelMae.setText("Mãe");

        jLabelPai.setText("Pai");

        jLabelEndereco.setText("Endereco");

        jLabel2.setText("Telefone");

        try {
            jFormattedTextFieldTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButtonAgendarAtendimento.setText("Agendar Atendimento");
        jButtonAgendarAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendarAtendimentoActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormattedTextFieldRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##.##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormattedTextFieldCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButtonLimpar.setText("Limpar Campos");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jComboBoxPesquisar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pesquisar", "Nome Paciente", "CPF" }));

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Novo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(15, Short.MAX_VALUE)
                                .addComponent(jComboBoxPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonPesquisar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNome)
                                    .addComponent(jLabelInscricao)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabelMae, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelCpf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelSexo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelPai, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabelEndereco)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldPai)
                                    .addComponent(jTextFieldMae)
                                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldEndereco)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonAgendarAtendimento))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jFormattedTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextFieldSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(64, 64, 64)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabelDataNascimento)
                                                    .addComponent(jLabelRg))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jFormattedTextFieldDataNascimento)
                                                    .addComponent(jFormattedTextFieldRg, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)))
                                            .addComponent(jTextFieldNome))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                        .addComponent(jLabel10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPesquisar)
                            .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInscricao)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSexo)
                    .addComponent(jTextFieldSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDataNascimento)
                    .addComponent(jFormattedTextFieldDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCpf)
                    .addComponent(jFormattedTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRg)
                    .addComponent(jFormattedTextFieldRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMae)
                    .addComponent(jTextFieldMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPai)
                    .addComponent(jTextFieldPai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEndereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAgendarAtendimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        try {

            EPaciente objp = new EPaciente();
            SimpleDateFormat formatadata = new SimpleDateFormat("dd/MM/yyyy");

            objp.setNome(jTextFieldNome.getText());
            objp.setSexo(jTextFieldSexo.getText());
            objp.setDatanascimento(new java.sql.Date(formatadata.parse(jFormattedTextFieldDataNascimento.getText()).getTime()));
            objp.setCpf(jFormattedTextFieldCpf.getText());
            objp.setRg(jFormattedTextFieldRg.getText());
            objp.setMae(jTextFieldMae.getText());
            objp.setPai(jTextFieldPai.getText());
            objp.setEndereco(jTextFieldEndereco.getText());
            objp.setTelefone(jFormattedTextFieldTelefone.getText());

//            new entidade.EFilaPaciente().enfileirar(objp);
            new negocio.NPaciente().salvar(objp);

            JOptionPane.showMessageDialog(principal, "Operação realizada com sucesso.");

            jTextFieldNome.setEnabled(false);
            jTextFieldId.setEnabled(false);
            jTextFieldMae.setEnabled(false);
            jTextFieldPai.setEnabled(false);
            jTextFieldSexo.setEnabled(false);
            jTextFieldEndereco.setEnabled(false);
            jFormattedTextFieldCpf.setEnabled(false);
            jFormattedTextFieldDataNascimento.setEnabled(false);
            jFormattedTextFieldRg.setEnabled(false);
            jFormattedTextFieldTelefone.setEnabled(false);

            jTextFieldNome.setText("");
            jTextFieldId.setText("");
            jTextFieldMae.setText("");
            jTextFieldPai.setText("");
            jTextFieldSexo.setText("");
            jTextFieldEndereco.setText("");
            jFormattedTextFieldCpf.setText("");
            jFormattedTextFieldDataNascimento.setText("");
            jFormattedTextFieldRg.setText("");
            jFormattedTextFieldTelefone.setText("");

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(principal, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed

        try {

            jTextFieldNome.setEnabled(true);
            jTextFieldId.setEnabled(true);
            jTextFieldMae.setEnabled(true);
            jTextFieldPai.setEnabled(true);
            jTextFieldSexo.setEnabled(true);
            jTextFieldEndereco.setEnabled(true);
            jFormattedTextFieldCpf.setEnabled(true);
            jFormattedTextFieldDataNascimento.setEnabled(true);
            jFormattedTextFieldRg.setEnabled(true);
            jFormattedTextFieldTelefone.setEnabled(true);
            jButtonSalvar.setEnabled(false);

            EPaciente objp = new EPaciente();
            SimpleDateFormat formatadata = new SimpleDateFormat("dd/MM/yyyy");

            objp.setId(Integer.parseInt(jTextFieldId.getText()));
            objp.setNome(jTextFieldNome.getText());
            objp.setSexo(jTextFieldSexo.getText());
            objp.setDatanascimento(new java.sql.Date(formatadata.parse(jFormattedTextFieldDataNascimento.getText()).getTime()));
            objp.setCpf(jFormattedTextFieldCpf.getText());
            objp.setRg(jFormattedTextFieldRg.getText());
            objp.setMae(jTextFieldMae.getText());
            objp.setPai(jTextFieldPai.getText());
            objp.setEndereco(jTextFieldEndereco.getText());
            objp.setTelefone(jFormattedTextFieldTelefone.getText());

            if (!jFormattedTextFieldCpf.getText().isEmpty()) {
                new persistencia.PPaciente().alterar(objp);
                JOptionPane.showMessageDialog(principal, "Alteração realizada com sucesso.");
                jTextFieldPesquisa.setText("");
                jTextFieldId.setText("");
                jTextFieldNome.setText("");
                jTextFieldSexo.setText("");
                jFormattedTextFieldDataNascimento.setText("");
                jFormattedTextFieldCpf.setText("");
                jFormattedTextFieldRg.setText("");
                jTextFieldMae.setText("");
                jTextFieldPai.setText("");
                jTextFieldEndereco.setText("");
                jFormattedTextFieldTelefone.setText("");

                jTextFieldNome.setEnabled(false);
                jTextFieldId.setEnabled(false);
                jTextFieldMae.setEnabled(false);
                jTextFieldPai.setEnabled(false);
                jTextFieldSexo.setEnabled(false);
                jTextFieldEndereco.setEnabled(false);
                jFormattedTextFieldCpf.setEnabled(false);
                jFormattedTextFieldDataNascimento.setEnabled(false);
                jFormattedTextFieldRg.setEnabled(false);
                jFormattedTextFieldTelefone.setEnabled(false);
                jButtonSalvar.setEnabled(true);
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(principal, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonAgendarAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendarAtendimentoActionPerformed

        try {
            AgendaAtendimento agenda = new AgendaAtendimento(this.principal);
            principal.add(agenda);
            agenda.setVisible(true);
            this.dispose();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(principal, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonAgendarAtendimentoActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed

        try {

            EPaciente consulta = new EPaciente();

            if (!jTextFieldPesquisa.getText().isEmpty()) {
                if (jComboBoxPesquisar.getSelectedItem() == "CPF") {
                    consulta.setCpf(jTextFieldPesquisa.getText());
                    consulta = new negocio.NAgendaAtendimento().consultarCpfPaciente(consulta.getCpf());
                } else {
                    if (jComboBoxPesquisar.getSelectedItem() == "Nome Paciente") {
                        consulta.setNome(jTextFieldPesquisa.getText());
                        consulta = new negocio.NAgendaAtendimento().ConsultarNomePaciente(consulta.getNome());

                    }
                }
            }
            


            jTextFieldId.setText(String.valueOf(consulta.getId()));
            jTextFieldNome.setText(consulta.getNome());
            jTextFieldSexo.setText(consulta.getSexo());
            jFormattedTextFieldDataNascimento.setText(String.valueOf(consulta.getDatanascimento()));
            jFormattedTextFieldCpf.setText(consulta.getCpf());
            jFormattedTextFieldRg.setText(consulta.getRg());
            jTextFieldMae.setText(consulta.getMae());
            jTextFieldPai.setText(consulta.getPai());
            jTextFieldEndereco.setText(consulta.getEndereco());
            jFormattedTextFieldTelefone.setText(consulta.getTelefone());

//            JOptionPane.showMessageDialog(principal, "Operação realizada com sucesso.");
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(principal, "Não houve resultado");
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed


    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed

        jTextFieldPesquisa.setText("");
        jTextFieldId.setText("");
        jTextFieldNome.setText("");
        jTextFieldSexo.setText("");
        jFormattedTextFieldDataNascimento.setText("");
        jFormattedTextFieldCpf.setText("");
        jFormattedTextFieldRg.setText("");
        jTextFieldMae.setText("");
        jTextFieldPai.setText("");
        jTextFieldEndereco.setText("");
        jFormattedTextFieldTelefone.setText("");

        jTextFieldNome.setEnabled(false);
        jTextFieldId.setEnabled(false);
        jTextFieldMae.setEnabled(false);
        jTextFieldPai.setEnabled(false);
        jTextFieldSexo.setEnabled(false);
        jTextFieldEndereco.setEnabled(false);
        jFormattedTextFieldCpf.setEnabled(false);
        jFormattedTextFieldDataNascimento.setEnabled(false);
        jFormattedTextFieldRg.setEnabled(false);
        jFormattedTextFieldTelefone.setEnabled(false);

    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextFieldNome.setEnabled(true);
        jTextFieldId.setEnabled(true);
        jTextFieldMae.setEnabled(true);
        jTextFieldPai.setEnabled(true);
        jTextFieldSexo.setEnabled(true);
        jTextFieldEndereco.setEnabled(true);
        jFormattedTextFieldCpf.setEnabled(true);
        jFormattedTextFieldDataNascimento.setEnabled(true);
        jFormattedTextFieldRg.setEnabled(true);
        jFormattedTextFieldTelefone.setEnabled(true);

        jTextFieldNome.setText("");
        jTextFieldId.setText("");
        jTextFieldMae.setText("");
        jTextFieldPai.setText("");
        jTextFieldSexo.setText("");
        jTextFieldEndereco.setText("");
        jFormattedTextFieldCpf.setText("");
        jFormattedTextFieldDataNascimento.setText("");
        jFormattedTextFieldRg.setText("");
        jFormattedTextFieldTelefone.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed

        try {
            EPaciente paciente = new EPaciente();
            EAgendaAtendimento agenda = new EAgendaAtendimento();

            if (!jTextFieldNome.getText().isEmpty()) {
                new negocio.NAgendaAtendimento().excluir(Integer.parseInt(jTextFieldId.getText()));
                paciente.setNome(jTextFieldNome.getText());
                new negocio.NPaciente().excluir(paciente.getNome());
                JOptionPane.showMessageDialog(principal, "Exclusão realizada com sucesso");
                jTextFieldPesquisa.setText("");
                jTextFieldId.setText("");
                jTextFieldNome.setText("");
                jTextFieldSexo.setText("");
                jFormattedTextFieldDataNascimento.setText("");
                jFormattedTextFieldCpf.setText("");
                jFormattedTextFieldRg.setText("");
                jTextFieldMae.setText("");
                jTextFieldPai.setText("");
                jTextFieldEndereco.setText("");
                jFormattedTextFieldTelefone.setText("");

                jTextFieldNome.setEnabled(false);
                jTextFieldId.setEnabled(false);
                jTextFieldMae.setEnabled(false);
                jTextFieldPai.setEnabled(false);
                jTextFieldSexo.setEnabled(false);
                jTextFieldEndereco.setEnabled(false);
                jFormattedTextFieldCpf.setEnabled(false);
                jFormattedTextFieldDataNascimento.setEnabled(false);
                jFormattedTextFieldRg.setEnabled(false);
                jFormattedTextFieldTelefone.setEnabled(false);
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(principal, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAgendarAtendimento;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxPesquisar;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpf;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataNascimento;
    private javax.swing.JFormattedTextField jFormattedTextFieldRg;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelDataNascimento;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelInscricao;
    private javax.swing.JLabel jLabelMae;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPai;
    private javax.swing.JLabel jLabelRg;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldMae;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPai;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldSexo;
    // End of variables declaration//GEN-END:variables
}
