/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import entidade.EPaciente;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Locale;
import java.util.Vector;
import javax.swing.JDesktopPane;
import javax.swing.JFormattedTextField;
import negocio.NPaciente;

/**
 *
 * @author Roberval
 */
public class PesquisaPaciente extends javax.swing.JInternalFrame {

    
    JDesktopPane principal;
    /**
     * 
     * Creates new form PesquisaPaciente
     */
    public PesquisaPaciente() {
        initComponents();
    }
    
    public PesquisaPaciente(JDesktopPane instancia){
        this();
        principal = instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxSelecao = new javax.swing.JComboBox();
        jTextFieldSelecao = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisaPaciente = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setTitle("Pesquisa Paciente");

        jComboBoxSelecao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nome", "CPF" }));

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jTablePesquisaPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTablePesquisaPaciente);

        jButton2.setText("Fechar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxSelecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSelecao, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSelecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSelecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed

//        try {
//
//            EPaciente paciente = new EPaciente();
//            NPaciente negocio = new NPaciente();
//            AgendaAtendimento agenda = new AgendaAtendimento();
//            SimpleDateFormat formatar = new SimpleDateFormat("dd/MM/yyyy");
//
//            Vector<String> cabecalho = new Vector<String>();
//            cabecalho.add("Paciente");
//            cabecalho.add("Médico");
//            cabecalho.add("Data Consulta");
//
//            Vector detalhe = new Vector();
//
//            if (!jTextFieldSelecao.getText().isEmpty()) {
//                if (jComboBoxSelecao.getSelectedItem() == "Nome") {
//                    paciente.setNome(jTextFieldSelecao.getText());
//                    
//                }
//                if(jComboBoxSelecao.getSelectedItem() == "CPF"){
//                    agenda.setDataconsulta(new java.sql.Date(formatar.parse(jTextFieldSelecao.getText()).getTime()));
//                    
//                }
//            }
//
            
//            List<EPaciente> retorno = negocio.listar(paciente);
//
//            for (EPaciente item : retorno) {
//                Vector<Object> linha = new Vector<>();
//                linha.add(item.getNome());
//                linha.add(item.get
//                linha.add(item.getTelefone());
//                linha.add(formatar.format(item.getDataNascimento()));
//                linha.add(item.getTipoAssociado().getDescricao());
//                detalhe.add(linha);
//            }
//
//            tblResultado.setModel(new DefaultTableModel(detalhe, cabecalho));
//
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this.principal, e.getMessage());
//        }
//
//
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JComboBox jComboBoxSelecao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePesquisaPaciente;
    private javax.swing.JTextField jTextFieldSelecao;
    // End of variables declaration//GEN-END:variables
}
